#include <vd2/VDXFrame/VideoFilterEntry.h>

VDX_DECLARE_VIDEOFILTERS_BEGIN()
	VDX_DECLARE_VIDEOFILTER(filterDef_verticalBlur)
	VDX_DECLARE_VIDEOFILTER(filterDef_yuvTransform)
VDX_DECLARE_VIDEOFILTERS_END()

VDX_DECLARE_VFMODULE()
