//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DeShaker.rc
//
#define IDD_CONFIG                      1000
#define RA_PASS1                        1000
#define RA_PASS2                        1001
#define ED_BLOCK_SIZE                   1002
#define ED_INIT_SEARCH_RANGE            1003
#define CG_IDC_PROGDLG_PROGRESS         1003
#define ED_DEEP_ANALYSIS_KICK_IN        1004
#define CB_SRC_ASPECT                   1005
#define CG_IDC_PROGDLG_STATUS           1005
#define CB_SCALE                        1006
#define CB_USE_PIXELS                   1007
#define ED_DISCARD_BLOCK_PIXELS         1008
#define CB_VIDEO_OUTPUT                 1009
#define ED_HOR_PAN                      1010
#define ED_VER_PAN                      1011
#define ED_ROTATION                     1012
#define ED_ZOOM                         1013
#define CB_DEST_ASPECT                  1014
#define ED_DEST_WIDTH                   1015
#define ED_DEST_HEIGHT                  1016
#define CB_RESAMPLING                   1017
#define ED_SEARCH_RANGE                 1018
#define ED_SKIP_FRAME                   1020
#define ED_EXTRA_ZOOM                   1021
#define CB_EDGE_COMP                    1022
#define GR_PASS1                        1023
#define ST_SRC_ASPECT                   1024
#define ST_VIDEO_OUTPUT                 1025
#define GR_MATCHING_PARAMS              1026
#define ST_BLOCK_SIZE                   1027
#define ST_BLOCK_SIZE2                  1028
#define ST_SCALE                        1030
#define ST_USE_PIXELS                   1031
#define ST_INIT_SEARCH_RANGE            1032
#define ST_INIT_SEARCH_RANGE2           1033
#define ST_SEARCH_RANGE                 1034
#define ST_SEARCH_RANGE2                1035
#define ST_DISCARD_BLOCK_PIXELS         1036
#define ST_DISCARD_BLOCK_PIXELS2        1037
#define ST_SKIP_FRAME                   1038
#define ST_SKIP_FRAME2                  1039
#define GR_PASS2                        1040
#define ST_DEST_ASPECT                  1041
#define ST_DEST_SIZE                    1042
#define ST_DEST_SIZE2                   1043
#define ST_RESAMPLING                   1044
#define GR_SMOOTHNESS                   1045
#define ST_HOR_PAN                      1046
#define ST_VER_PAN                      1047
#define ST_ROTATION                     1048
#define ST_ZOOM                         1049
#define ST_EDGE_COMP                    1050
#define ST_DISCARD_MATCH                1051
#define ED_DISCARD_MATCH                1052
#define ST_EXTRA_ZOOM                   1053
#define ST_DISCARD_MATCH2               1054
#define ST_DISCARD_2ND_MATCH            1055
#define ED_DISCARD_2ND_MATCH            1056
#define ST_VIDEO_TYPE                   1057
#define CB_VIDEO_TYPE                   1058
#define ST_DEEP_ANALYSIS_KICK_IN2       1059
#define ST_MULTI_FRAME_BORDER           1060
#define ED_DISCARD_BLOCK_ABS_PIXELS     1061
#define CG_IDD_PROGRESS                 1062
#define ST_DISCARD_BLOCK_ABS_PIXELS     1062
#define ED_LOGFILE                      1063
#define IDD_CONFIG_SMALL                1063
#define PB_LOGFILE_BROWSE               1064
#define ST_DISCARD_BLOCK_ABS_PIXELS2    1065
#define ED_ERS                          1066
#define ST_ERS                          1067
#define GR_LIMITS                       1068
#define ST_LIMIT_HOR_PAN                1069
#define ED_LIMIT_HOR_PAN                1070
#define ST_LIMIT_VER_PAN                1072
#define ED_LIMIT_VER_PAN                1073
#define ST_LIMIT_ROTATION               1074
#define CX_LOGFILE_APPEND               1075
#define ST_LOGFILE                      1076
#define GR_DISCARD                      1077
#define GR_IGNORE_AREA                  1078
#define ST_IGNORE_LEFT                  1079
#define ST_IGNORE_RIGHT                 1080
#define ST_IGNORE_TOP                   1081
#define ST_IGNORE_BOTTOM                1082
#define CX_IGNORE_OUTSIDE               1083
#define CX_IGNORE_INSIDE                1084
#define ED_IGNORE_OUTSIDE_LEFT          1085
#define ED_IGNORE_OUTSIDE_RIGHT         1086
#define ED_IGNORE_OUTSIDE_TOP           1087
#define ED_IGNORE_OUTSIDE_BOTTOM        1088
#define ED_IGNORE_INSIDE_LEFT           1089
#define ED_IGNORE_INSIDE_RIGHT          1090
#define ED_IGNORE_INSIDE_TOP            1091
#define ED_IGNORE_INSIDE_BOTTOM         1092
#define ED_LIMIT_ROTATION               1093
#define ST_LIMIT_ZOOM                   1094
#define ED_LIMIT_ZOOM                   1095
#define CG_IDS_PROGRESS_CAPTION         1096
#define ST_FROM_BORDER                  1096
#define CX_USE_OLD_AND_FUTURE_FRAMES    1097
#define ED_LOGFILE2                     1098
#define ST_LOGFILE2                     1099
#define ED_OLD_FRAMES                   1100
#define ST_LOGFILE3                     1101
#define ED_FUTURE_FRAMES                1102
#define ST_FUTURE_FRAMES                1103
#define ST_OLD_FRAMES                   1104
#define CX_FOLLOW_IGNORE_OUTSIDE        1105
#define ST_DEEP_ANALYSIS_KICK_IN        1106
#define CX_ERS                          1107
#define ED_NEW_SCENE                    1108
#define CX_INTERLACED_PROGRESSIVE_DEST  1109
#define CX_DEST_SAME_AS_SRC             1110
#define CX_MULTI_FRAME_BORDER           1111
#define CX_EXTRAPOLATE_BORDER           1112
#define CX_USE_COLOR_MASK               1113
#define PB_VISIT_WEB                    1114
#define ST_DISCARD_PIXEL_DIFF           1115
#define ED_ADAPTIVE_ZOOM_SMOOTHNESS     1116
#define ED_DISCARD_PIXEL_DIFF           1117
#define ED_EDGE_TRANSITION_PIXELS       1118
#define ST_DISCARD_PIXEL_DIFF2          1119
#define CX_REMEMBER_DISCARDED_AREAS     1120
#define ST_CPUS                         1121
#define TE_CPUS                         1122
#define ST_ERS2                         1123
#define CX_DETECT_ROTATION              1124
#define CX_DETECT_ZOOM                  1125
#define ED_ADAPTIVE_ZOOM_AMOUNT         1126
#define ST_ADAPTIVE_ZOOM                1127
#define ST_ADAPTIVE_ZOOM2               1128
#define ST_ADAPTIVE_ZOOM3               1129
#define PB_LOGFILE_DELETE               1130
#define PB_LOGFILE_OPEN                 1131
#define PB_LOGFILE_OPEN_FOLDER          1132
#define CX_NEW_SCENE                    1133
#define ST_MULTI_FRAME_BORDER2          1135
#define CBT_MASK_COLOR                  1138

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1002
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1139
#define _APS_NEXT_SYMED_VALUE           1097
#endif
#endif
